name: Run Python Script Every Day at 11 AM

on:
  schedule:
    - cron: "0 11 * * 1-5"  # Runs at 11:00 AM UTC (Monday to Friday)
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main  # Ensure we're on the main branch (or change to the branch you want)

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"  # Uses the latest Python 3 version

      - name: Run Python Script
        run: python morning_check.py  # Runs your script
        
      - name: Check if CSV exists before committing
        run: |
          if [ -f "reports/morning_check_test.csv" ]; then
            echo "CSV file exists, proceeding to commit."
          else
            echo "CSV file does not exist, exiting."
            exit 1
          fi
          
      - name: Commit and Push CSV File to Repository
        run: |
          git config --global user.name "kkaliagina"
          git config --global user.email "k.kaliagina@exchange-data.com"
          git add reports/morning_check.csv  # Path to the generated CSV file
          git commit -m "Add morning_check.csv generated by script"
          git push origin main  # Push to the main branch (or the branch you're working on)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's token to authenticate the push
